# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_get_lp__ <- function(thetas_by_col, target_log_pdf) {
    .Call(`_ehmc_rcpp_get_lp__`, thetas_by_col, target_log_pdf)
}

rcpp_get_sampling_weights <- function(thetas_by_col, proposal_log_pdf_val, target_log_pdf) {
    .Call(`_ehmc_rcpp_get_sampling_weights`, thetas_by_col, proposal_log_pdf_val, target_log_pdf)
}

rcpp_adapt_pars <- function(thetas_by_col, weights, target_log_pdf, target_grad_log_pdf, control) {
    .Call(`_ehmc_rcpp_adapt_pars`, thetas_by_col, weights, target_log_pdf, target_grad_log_pdf, control)
}

rcpp_run <- function(iter, start, leaps_vector, stepsizes_vector, weights, target_log_pdf, target_grad_log_pdf, inv_m, metric_str, refresh_rate, random) {
    .Call(`_ehmc_rcpp_run`, iter, start, leaps_vector, stepsizes_vector, weights, target_log_pdf, target_grad_log_pdf, inv_m, metric_str, refresh_rate, random)
}

what_metric_type <- function(m) {
    .Call(`_ehmc_what_metric_type`, m)
}

