// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_get_lp__
Rcpp::NumericVector rcpp_get_lp__(const arma::mat& thetas_by_col, const Rcpp::Function& target_log_pdf);
RcppExport SEXP _ehmc_rcpp_get_lp__(SEXP thetas_by_colSEXP, SEXP target_log_pdfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type thetas_by_col(thetas_by_colSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type target_log_pdf(target_log_pdfSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_lp__(thetas_by_col, target_log_pdf));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_sampling_weights
Rcpp::List rcpp_get_sampling_weights(const arma::mat& thetas_by_col, const arma::vec& proposal_log_pdf_val, const Rcpp::Function& target_log_pdf);
RcppExport SEXP _ehmc_rcpp_get_sampling_weights(SEXP thetas_by_colSEXP, SEXP proposal_log_pdf_valSEXP, SEXP target_log_pdfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type thetas_by_col(thetas_by_colSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type proposal_log_pdf_val(proposal_log_pdf_valSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type target_log_pdf(target_log_pdfSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_sampling_weights(thetas_by_col, proposal_log_pdf_val, target_log_pdf));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_adapt_pars
Rcpp::List rcpp_adapt_pars(const arma::mat& thetas_by_col, const arma::vec& weights, const Rcpp::Function& target_log_pdf, const Rcpp::Function& target_grad_log_pdf, const Rcpp::List& control);
RcppExport SEXP _ehmc_rcpp_adapt_pars(SEXP thetas_by_colSEXP, SEXP weightsSEXP, SEXP target_log_pdfSEXP, SEXP target_grad_log_pdfSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type thetas_by_col(thetas_by_colSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type target_log_pdf(target_log_pdfSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type target_grad_log_pdf(target_grad_log_pdfSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_adapt_pars(thetas_by_col, weights, target_log_pdf, target_grad_log_pdf, control));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_run
Rcpp::List rcpp_run(size_t iter, const arma::vec& start, const arma::Col<size_t>& leaps_vector, const arma::vec& stepsizes_vector, const arma::vec& weights, const Rcpp::Function& target_log_pdf, const Rcpp::Function& target_grad_log_pdf, const arma::mat& inv_m, std::string metric_str, double refresh_rate, bool random);
RcppExport SEXP _ehmc_rcpp_run(SEXP iterSEXP, SEXP startSEXP, SEXP leaps_vectorSEXP, SEXP stepsizes_vectorSEXP, SEXP weightsSEXP, SEXP target_log_pdfSEXP, SEXP target_grad_log_pdfSEXP, SEXP inv_mSEXP, SEXP metric_strSEXP, SEXP refresh_rateSEXP, SEXP randomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::Col<size_t>& >::type leaps_vector(leaps_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type stepsizes_vector(stepsizes_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type target_log_pdf(target_log_pdfSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type target_grad_log_pdf(target_grad_log_pdfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type inv_m(inv_mSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric_str(metric_strSEXP);
    Rcpp::traits::input_parameter< double >::type refresh_rate(refresh_rateSEXP);
    Rcpp::traits::input_parameter< bool >::type random(randomSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_run(iter, start, leaps_vector, stepsizes_vector, weights, target_log_pdf, target_grad_log_pdf, inv_m, metric_str, refresh_rate, random));
    return rcpp_result_gen;
END_RCPP
}
// what_metric_type
std::string what_metric_type(const arma::mat& m);
RcppExport SEXP _ehmc_what_metric_type(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(what_metric_type(m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ehmc_rcpp_get_lp__", (DL_FUNC) &_ehmc_rcpp_get_lp__, 2},
    {"_ehmc_rcpp_get_sampling_weights", (DL_FUNC) &_ehmc_rcpp_get_sampling_weights, 3},
    {"_ehmc_rcpp_adapt_pars", (DL_FUNC) &_ehmc_rcpp_adapt_pars, 5},
    {"_ehmc_rcpp_run", (DL_FUNC) &_ehmc_rcpp_run, 11},
    {"_ehmc_what_metric_type", (DL_FUNC) &_ehmc_what_metric_type, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ehmc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
